version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - contacts-net
    env_file:
      - .env

  app:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - contacts-net
    env_file:
      - .env

volumes:
  postgres_data:

networks:
  contacts-net:
